### PR TITLE
[JBJCA-1422] MaxWaitCount will be counted one less than waiting requests

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/JBJCA-1422
JBEAP issue: https://issues.redhat.com/browse/JBEAP-21012

also Java text formatted.

### CODE REVIEW

**Comment by spyrkob** [comment]
@moulalis I'm not sure this formatting is correct - AFAIK the rest of the project uses opening bracket on new line convention and 3 spaces indentation. I don't think it should be changed in a single class and definitely not in the same commit as a bug fix.

**Comment by moulalis** [comment]
> @moulalis I'm not sure this formatting is correct - AFAIK the rest of the project uses opening bracket on new line convention and 3 spaces indentation. I don't think it should be changed in a single class and definitely not in the same commit as a bug fix.

@spyrkob Its clean now, I had used IDE provided formatter, removed it now.

**Comment by spyrkob** [comment]
Thanks @moulalis

@tadamski could you review when you have a moment?

**Review by tadamski — COMMENTED** [review]
The calculation looks good, but I still have doubts that I shared in the Jira:
Shouldn't this calculate value be placed in WaitCount instead? My understanding of docs is that MaxWaitCount should be an aggregate.

**Comment by spyrkob** [comment]
Thanks @tadamski!

My understanding of [1] was that MaxWaitCount should represents peak count of waiting threads (which AFAIU [2] is doing) and WaitCount would be an aggregate count of all thread that had to wait for connection. 

I think maybe WaitCount should be renamed to TotalWaitCount and the docs could be clarified, but would it be better to deal with it in a separate issue?

[1] https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/configuration_guide/reference_material#reference_of_datasource_statistics
[2] https://github.com/ironjacamar/ironjacamar/blob/6416217dd93d3689c1266f6c3b81433778b37cf1/core/src/main/java/org/jboss/jca/core/connectionmanager/pool/PoolStatisticsImpl.java#L931-L935

**Comment by gaol** [comment]
@moulalis JBEAP issue should be https://issues.redhat.com/browse/JBEAP-21012

@tadamski I agree with @spyrkob as well, although the name maybe confusing. [The implementation](https://github.com/ironjacamar/ironjacamar/blob/ironjacamar-1.4.31.Final/core/src/main/java/org/jboss/jca/core/connectionmanager/pool/mcp/SemaphoreConcurrentLinkedDequeManagedConnectionPool.java#L301) about `WaitCount` also tells that it represents the aggregate count of all waiting calls intentionally.  :)

**Review by tadamski — APPROVED** [review]

**Comment by tadamski** [comment]
merged @moulalis could you please open analogous PR for 2.0?

**Comment by moulalis** [comment]
> merged @moulalis could you please open analogous PR for 2.0?

@tadamski 2.0 PR https://github.com/ironjacamar/ironjacamar/pull/727 created.

**Pull request merged**
