### PR TITLE
[JBJCA-1276] Prefill race condition in flush

### PR DESCRIPTION
**Pull request by dpospisil**
JIRA: https://issues.jboss.org/browse/JBJCA-1276
BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1231658

### CODE REVIEW

**Comment by jesperpedersen** [comment]
This PR isn't correct - see the 1.2 branch

**Comment by jesperpedersen** [comment]
Nope, still wrong. Hint, prefill is default false - create a user forum thread on the matter for more.

And pull requests needs to be squashed, and rebased before submitting

**Comment by jesperpedersen** [comment]
Nope, still  not

**Comment by dpospisil** [comment]
@jasperpedersen is it OK finally?

**Comment by jesperpedersen** [comment]
Merged

**Pull request merged**
