### PR TITLE
[BZ1100839] : Intermittent fail of some datasource tests on IBM JDK after attempt to load mysql driver for h2 datasource

### PR DESCRIPTION
**Pull request by panossot**
[BZ1100839] : https://bugzilla.redhat.com/show_bug.cgi?id=1100839 

Fixes the IBM JDK 1.6 issue by getting the LocalManagedConnection after reloading the driver when the first try fails.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Can one of the admins verify this patch?

**Comment by jesperpedersen** [comment]
That is a hack for what looks like a JDK issue.

Use <allocation-retry> instead

**Comment by panossot** [comment]
<allocation-retry> does not solve the problem. The same error log is produced.

**Comment by jesperpedersen** [comment]
Well, we are not doing retry logic inside a resource adapter, that is the job of the container

**Pull request closed without merging**
