### PR TITLE
RADeployer can manage jar file who contains rar resources now

### PR DESCRIPTION
**Pull request by tcollignon**
Hello

Like I said in #534, I wish use RaDaployer with jar file. Indeed I have RAR resources (_jdbc-xa.rar_) but I want to manage this easyly with Maven, so I have made a jar who contains this rar file. 
This PR provide ability of RADeployer to manage this kind of resources, in jar file.

### CODE REVIEW

**Comment by maeste** [comment]
General comments:
* It needs a rebase
* don't use * in import
* open a discussion on google groups forum to discuss how to implement this also in 2.x series to don't forget it during our new deployment

Thanks a lot for you interest and contribution

**Comment by tcollignon** [comment]
Thank you for replying
I will push another commit with your recommandation
For google group I have start new post, but it doesn't appaear, you need to accept this, or I have made a mistake?
Thank you

**Comment by maeste** [comment]
Sorry for that, just removed your post from spam, and replied w/ my comments on general idea.
Thanks again for the interest.

regards
S.

**Comment by maeste** [comment]
surpassed by https://github.com/ironjacamar/ironjacamar/pull/559

**Pull request closed without merging**
