### PR TITLE
Expression tests for ironjacamar and resourceadapter

### PR DESCRIPTION
**Pull request by ABalyaev**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Could you squash these commits ?

**Comment by ABalyaev** [comment]
Hi Jesper,
Done.

**Comment by vratsel** [comment]
Andrey, please take a look at your commit and rebase it against the upstream/master branch

**Comment by ABalyaev** [comment]
Vladimir, I did rebase. Please check that now it's ok.

**Comment by vratsel** [comment]
now it looks OK IMO

**Comment by jesperpedersen** [comment]
You may find it easier to develop on a feature branch instead of directly on master.

Merged, thanks for your contribution

**Pull request merged**
