### PR TITLE
Add protection in DsXmlDeployer to prevent from loading xml resource …

### PR DESCRIPTION
**Pull request by tcollignon**
…in jar file, and add possibility of override this class

As I have done in #559 , I propose this PR to do exactly the same thing for DsXmlDeployer.

My goal is to allow a custom DsXmlDeployer file who Override DsXmlDeployer and manage xml datasource loacted in jar file.

### CODE REVIEW

**Comment by tcollignon** [comment]
Hi

Ok I have open this : https://issues.jboss.org/browse/JBJCA-1333 
Is it ok ?

I have try to subscribre in https://cla.jboss.org/index.seam  in "jboss tools" category, is it the good one? (I don't see ironjacamar)

Thanks

**Comment by maeste** [comment]
Issue is ok. Please reword your commit comment and push -f your branch.

Sign CLA under "JBoss Application Server" please.

Thanks again
S.

**Comment by tcollignon** [comment]
Ok I have reword my commit
and I have sign to Jboss Application Server

**Comment by tcollignon** [comment]
Thank you !

Have you cherry-pick this on 1.3 too ?

Thanks again

**Comment by maeste** [comment]
No yet, feel free do it yourself submitting another PR ;)

**Comment by tcollignon** [comment]
Ok no problem (last time you do this, that's why I ask)
I need to make another issue or I sumbit with the same number?
Thanks

**Comment by maeste** [comment]
The same issue is fine,  just cherry pick the commit. 
I'm asking you just to give you more kudos in the project / github 
Regards
S.

**Pull request merged**
