### PR TITLE
[JBJCA-1294] - remove isTraceEnabled caching

### PR DESCRIPTION
**Pull request by baranowb**
https://issues.jboss.org/browse/JBJCA-1294
https://bugzilla.redhat.com/show_bug.cgi?id=1259840

1.0 PR https://github.com/ironjacamar/ironjacamar/pull/406

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Is this ready for review now ? Or do you have an ETA ?

Otherwise close, and reopen once ready

**Comment by baranowb** [comment]
Yes, it should be "good to go".

**Comment by jesperpedersen** [comment]
Merge conflict

**Comment by jesperpedersen** [comment]
Merged

**Pull request merged**
