### PR TITLE
[JBJCA-1386] adding TCCL in Wrapper*

### PR DESCRIPTION
**Pull request by spyrkob**
JIRA: https://issues.jboss.org/browse/WFLY-10798, https://issues.jboss.org/browse/JBJCA-1386

### CODE REVIEW

**Comment by fl4via** [comment]
I'm rerunning the travis build, something went wrong while downloading the JDK8 installer...

**Comment by spyrkob** [comment]
Created JBCJA-1386 and updated the commit description. Thanks!

**Comment by spyrkob** [comment]
@fl4via I think the test failure is not related to the change, is it possible to re-run the tests?

**Comment by fl4via** [comment]
I'm rerunnign the tests and I'll merge as soon as they pass.

**Pull request merged**
